# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('razao', models.CharField(max_length=100)),
                ('login_moip', models.CharField(max_length=100)),
                ('boleto_imagem', models.FileField(blank=True, null=True, upload_to='uploads/moip/img/')),
                ('url_notificacao', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()])),
                ('url_retorno', models.CharField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('url_ambiente', models.TextField(max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('token_moip', models.CharField(max_length=200)),
                ('key_moip', models.CharField(max_length=200)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('formas_pagamento', models.ManyToManyField(related_name='formas_pagamento', to='moip.FormaPagamento')),
            ],
        ),
    ]
